// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

var inputFilePath = Path.join(__dirname, "./input.txt");

function readFile(param) {
  return Fs.readFileSync(inputFilePath, "utf8");
}

function compareChars(a, b) {
  var match = a < 91;
  var match$1 = b < 91;
  if (match) {
    if (match$1) {
      return false;
    } else {
      return (a + 32 | 0) === b;
    }
  } else if (match$1) {
    return a === (32 + b | 0);
  } else {
    return false;
  }
}

function minimize(line) {
  var _minimizedLine = line;
  var _idx = 0;
  while(true) {
    var idx = _idx;
    var minimizedLine = _minimizedLine;
    var match = minimizedLine.length === 0;
    if (match) {
      return "";
    } else {
      var match$1 = (minimizedLine.length - 1 | 0) === idx;
      if (match$1) {
        return minimizedLine;
      } else {
        var match$2 = compareChars(Caml_string.get(minimizedLine, idx), Caml_string.get(minimizedLine, idx + 1 | 0));
        if (match$2) {
          _idx = 0;
          _minimizedLine = minimizedLine.slice(0, idx) + minimizedLine.slice(idx + 2 | 0);
          continue ;
        } else {
          _idx = idx + 1 | 0;
          continue ;
        }
      }
    }
  };
}

console.log(minimize(Fs.readFileSync(inputFilePath, "utf8")).length);

exports.inputFilePath = inputFilePath;
exports.readFile = readFile;
exports.compareChars = compareChars;
exports.minimize = minimize;
/* inputFilePath Not a pure module */
