// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Path = require("path");
var $$Array = require("bs-platform/lib/js/array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

var inputFilePath = Path.join(__dirname, "./input.txt");

var data = Fs.readFileSync(inputFilePath, "utf8");

function dataToInts(data) {
  return data.split("\n").map((function (line) {
                var match = line.startsWith("-");
                if (match) {
                  return Caml_int32.imul(-1, Caml_format.caml_int_of_string(line.slice(1)));
                } else {
                  return Caml_format.caml_int_of_string(line.slice(1));
                }
              }));
}

function add(dataPoints) {
  return $$Array.fold_left((function (total, dataPoint) {
                return total + dataPoint | 0;
              }), 0, dataPoints);
}

console.log(add(dataToInts(data)));

exports.inputFilePath = inputFilePath;
exports.data = data;
exports.dataToInts = dataToInts;
exports.add = add;
/* inputFilePath Not a pure module */
